// 02-s3-builds/02-s3-static-page-02/src/components/MyCounter.tsx
import React, { useState } from "react";

const MyCounter = () => {
  const [counter, setCounter] = useState(0);

  const buttonsInfo = {
    increase: 1,
    decrease: -1,
  };

  const buttonNames = Object.keys(buttonsInfo) as Array<keyof typeof buttonsInfo>

  const onClick = (name: keyof typeof buttonsInfo) => {
    setCounter(counter => counter + buttonsInfo[name]);
  };

  const parseToButtonName = (name: string) => {
    return name[0].toUpperCase() + name.substring(1);
  };

  return (
    <div className="MyCounter">
      <h2 className="MyCounter-value">
        카운터: {counter}
      </h2>

      <div className="MyCounter-actions">
        {buttonNames.map(name => (
          <button
            key={name}
            className="MyCounter-actions-button"
            onClick={() => onClick(name)}
          >
            {parseToButtonName(name)}
          </button>
        ))}
      </div>
    </div>
  );
};

export default MyCounter;

// 02-s3-builds/02-s3-static-page-01/src/components/MyCounter.vue
<template>
  <div class="MyCounter">
    <h2 class="MyCounter-counter">
      카운터: {{ counter }}
    </h2>

    <div class="MyCounter-wrapper">
      <button 
        v-for="name in buttons"
        :key="name"
        @click="() => onClick(name)"
        :name="name"
        class="MyCounter-wrapper-button"
      >
        {{ parseToCamel(name) }}
      </button>
    </div>
  </div>
</template>

<script>
import { 
  defineComponent,
  ref,
  reactive,
  computed,
} from "vue";

export default defineComponent({
  setup() {
    const counter = ref(0);

    const buttonInfos = reactive({
      increase: 1,
      decrease: -1,
    });

    const buttons = computed(() => Object.keys(buttonInfos));

    const parseToCamel = name => {
      return name[0].toUpperCase() + name.substring(1);
    }

    const onClick = name => {
      counter.value += buttonInfos[name]
    }

    return {
      counter,
      buttons,
      onClick,
      parseToCamel,
    };
  },
});
</script>

<style>
.MyCounter-wrapper-button {
  margin: 0 4px;
}
</style>
